AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal infrastructure for Lambda + RDS'

Parameters:
  S3Key:
    Type: String
    Description: S3 key for the Lambda deployment package
    Default: lambda-function.zip
  PostgreSQLHost:
    Type: String
    Description: PostgreSQL RDS endpoint
    Default: ""
  PostgreSQLDatabase:
    Type: String
    Description: PostgreSQL database name
    Default: postgres
  PostgreSQLUsername:
    Type: String
    Description: PostgreSQL username
    Default: masteruser
  PostgreSQLPassword:
    Type: String
    Description: PostgreSQL password
    Default: Password2123
    NoEcho: true
  AWSLambdaRegion:
    Type: String
    Description: AWS Lambda region
    Default: us-east-1

Conditions:
  HasPostgreSQLHost: !Not [!Equals [!Ref PostgreSQLHost, ""]]

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: BookLendingVPC

  # Private Subnets for Lambda and RDS
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet2

  # Security Groups
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref MyVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS from Lambda
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  # Lambda Function
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BookLendingLambda
      Handler: BookLendingApp::BookLendingApp.LambdaEntryPoint::FunctionHandlerAsync
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: lambda-deployment-565393029483-us-east-1
        S3Key: !Ref S3Key
      Runtime: dotnet8
      Timeout: 30
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          USE_SSM: 'false'
          POSTGRESQL_HOST: !If [HasPostgreSQLHost, !Ref PostgreSQLHost, !GetAtt MyRDSInstance.Endpoint.Address]
          POSTGRESQL_DATABASE: !Ref PostgreSQLDatabase
          POSTGRESQL_USERNAME: !Ref PostgreSQLUsername
          POSTGRESQL_PASSWORD: !Ref PostgreSQLPassword
          AWS_LAMBDA_REGION: !Ref AWSLambdaRegion
  # RDS Subnet Group
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  # RDS Instance
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: booklending-postgres
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '16.4'
      MasterUsername: masteruser
      MasterUserPassword: Password2123
      AllocatedStorage: '20'
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
      DeletionProtection: false

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref MyLambdaFunction
    Export:
      Name: BookLendingLambdaName
      
  RDSEndpoint:
    Description: RDS endpoint
    Value: !GetAtt MyRDSInstance.Endpoint.Address
    Export:
      Name: BookLendingRDSEndpoint