name: Deploy to AWS Lambda via S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lambda package
        run: zip -r lambda-function.zip . -x ".git/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Upload to S3
        run: aws s3 cp lambda-function.zip s3://lambda-deployment-565393029483-us-east-1/lambda-function.zip

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name myLambdaFunction \
            --s3-bucket lambda-deployment-565393029483-us-east-1 \
            --s3-key lambda-function.zip