name: Deploy to AWS Lambda via S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Build and Package Lambda
        run: |
          cd src
          dotnet lambda package --configuration Release --framework net8.0 --output-package ../deployment/lambda-function.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Upload to S3
        run: aws s3 cp deployment/lambda-function.zip s3://lambda-deployment-565393029483-us-east-1/lambda-function.zip

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name MyLambdaFunction \
            --s3-bucket lambda-deployment-565393029483-us-east-1 \
            --s3-key lambda-function.zip
          aws lambda update-function-configuration \
            --function-name MyLambdaFunction \
            --handler "BookLendingApp::BookLendingApp.LambdaEntryPoint::FunctionHandlerAsync"